---
# ScoreTag Configuation:
# use § or & for color:

ScoreTag: "§3§lPing: &d{ping}"

#ScoreTag List:
#{name} - show player name.
#{tps} - show server TickPerSecond.
#{online} - shows the count of how much player is online.
#{max_online} - get server max online.
#{x}/{y}/{z} - get player position position xyz.
#{level} - shows world name.
#{id}:{ids} - Shows what item ID holding.
#{item} - shows the player holding item name.
#{usage} - Shows the server TickUsage.
#{ping} - shows the player ping.
#{cps} - shows the player CPS.
...